name: Testes de Unidade e Integração

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar o ambiente de teste
      run: |
        # Defina a versão do .NET explicitamente
        dotnet --version
        dotnet restore

        # Instale o Entity Framework Core localmente
        dotnet tool install dotnet-ef --version 6.0.100 --local || true
      shell: bash

    - name: Executar testes de unidade e integração
      run: |
        dotnet test MiniProjetoWakeTests/MiniProjetoWakeTests.csproj --no-restore --verbosity normal
      shell: bash

    - name: Limpar o cache do NuGet
      run: dotnet nuget locals all --clear
